### ISSUE TITLE
Typetura NPM issue

### ISSUE THREAD

**Issue by SteamTrainCreative** [typetura/typetura.js#19]
My keyframes works when I use a script tag but not via the npm. Why would that be?

**Comment by scottkellum** [comment]
Related project: https://github.com/SteamTrainCreative/Boilerplate/blob/master/package.json

**Comment by scottkellum** [comment]
@SteamTrainCreative Thank you for creating this issue! Are you running this with a node server?

**Comment by scottkellum** [comment]
I downloaded your project and the script is in the `node_modules` folder, but you need to be running a node server in order to use the js import. I can work to make that more clear in the documentation if that will be helpful.

**Comment by SteamTrainCreative** [comment]
We are creating static websites hosted on netlify...this means that we can't use typetura?
That's would be sad...

**Comment by scottkellum** [comment]
Typetura will work here, and there are a few approaches you can take. Before getting into those here is what is going on. It looks like you are using Node to manage dependencies and compile Sass, but you’re not using it for markup or script compilation. This means you don’t have any system in place to route the typetura script in your node modules to the pages you are working with. So here’s how you might be able to do this:

1. Link directly to the file in `node_modules`. You will need to make sure this exists when deploying to Netlify or you can make some system to pull whatever version you are using into your main directory. Here is what a link to `node_modules` would look like: `<script src="node_modules/typeturajs/js/typetura.min.js"></script>`
2. Drop this file into your project and manually update it instead of using NPM to update it: https://github.com/typetura/typetura.js/blob/master/js/typetura.min.js
3. Use some kind of `npm run start` and `npm run build` set up that flattens your node modules into your project. This will let you use the `common js` line from the readme. Pinging @clickclickonsal to weigh in on this as he is more of a node expert than me. All this stuff is built into modern JS frameworks like React and Vue.

**Comment by SteamTrainCreative** [comment]
Thanks for the support. We will go on option #2 for now. How often do you think we would have to update this file?

**Comment by scottkellum** [comment]
@SteamTrainCreative Not often at all. There isn’t much to it so not much to change. I have been playing around with when to write the initial styles so I may change that soon. Currently it’s on load but I may change it back do document ready.

In about a year or so, when CSS register properties lands in browsers, I plan on another release. This will include some modular scale additions but the core that exists currently will not change much.

**Comment by SteamTrainCreative** [comment]
This is very exciting stuff @scottkellum, all the best in your efforts with this project. I heard about you on ShopTalk show and immediately knew I wanted to use Typetura for our clients. All the best and hope more people will pay attention your project.

**Comment by scottkellum** [comment]
@SteamTrainCreative Thank you! I appreciate it 😄

If you have any other questions, comments, thoughts, or ideas don’t hesitate to reach out!
